### ISSUE TITLE
Issue: Yarn PnP throws an error because "@apollo-client-react-streaming" requires "graphql" but does not list it as a dependency

### ISSUE THREAD

**Issue by Rewwoken** [apollographql/apollo-client-nextjs#417]
### Issue
If [pnpMode](https://yarnpkg.com/configuration/yarnrc#pnpMode) is set to `"strict"` (which is the default value), modules won't be allowed to require packages they don't explicitly list in their own dependencies.

Yarn PnP throws an error because of [transportedOptions.ts#L8](https://github.com/apollographql/apollo-client-nextjs/blob/c125a08d88cdcf291d54e58cbd42f10363b97912/packages/client-react-streaming/src/DataTransportAbstraction/transportedOptions.ts#L8) import statement which imports `graphql` package, but [this package is listed in devDependencies](https://github.com/apollographql/apollo-client-nextjs/blob/c125a08d88cdcf291d54e58cbd42f10363b97912/packages/client-react-streaming/package.json#L154).

![Image](https://github.com/user-attachments/assets/5d62888c-62e6-4a8f-85f2-9f51ab5fb9cd)

### Suggested change
I suggest moving `graphql` package from `devDependencies` to `dependencies`.

### Workarounds for now:
In `.yarnrc.yml`, either set `pnpMode` to `loose`
```yml
pnpMode: loose
```
or explicitly list  `graphql` as a dependency
```yml
packageExtensions:
  # Package requires `graphql` but doesn't list it as a dependency
  "@apollo/client-react-streaming@*":
    dependencies:
      "graphql": "*"
```

I hope I’ve understood the problem correctly. Please let me know if there are any inaccuracies.
